# Generated by Django 3.2.6 on 2021-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20210830_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
