# Generated by Django 3.2.6 on 2021-09-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_alter_author_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
